# Generated by Django 3.0.4 on 2020-03-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.IntegerField()),
                ('Time_start', models.CharField(max_length=30)),
                ('Time_end', models.CharField(max_length=30)),
                ('Sequence', models.IntegerField()),
                ('Subtitle', models.TextField()),
                ('Audio', models.FileField(upload_to='Audio/')),
                ('Video', models.FileField(upload_to='Video/')),
            ],
        ),
        migrations.CreateModel(
            name='uploaded_audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Audio', models.FileField(upload_to='uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(upload_to='uploaded')),
                ('Sub', models.FileField(upload_to='uploaded')),
            ],
        ),
    ]
